### ISSUE TITLE
Kaae error on scheduler.js taking kibana down

### ISSUE THREAD

**Issue by guilhermef** [elasticfence/kaae#50]
I've installed the latest snapshot on Kibana4, and created a new watcher:
```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "MRTS - response time",
  "_new": "true",
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 1 minute"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": "mrts-stash-*",
          "body": {
            "query": {
              "filtered": {
                "query": {
                  "query_string": {
                    "query": "message:\"Request Done\"",
                    "analyze_wildcard": true
                  }
                },
                "filter": {
                  "range": {
                    "@timestamp": {
                      "from": "now-1h"
                    }
                  }
                }
              }
            },
            "aggs": {
              "response_time": {
                "percentiles": {
                  "field": "time_used",
                  "percents": [
                    95
                  ]
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.aggregations.response_time.values['95.0'] > 4"
      }
    },
    "transform": {},
    "actions": {
      "email_admin": {
        "throttle_period": "1m",
        "email": {
          "to": "example@example.com",
          "from": "kaae@localhost",
          "subject": "KAAE ALARM {{ payload._id }}",
          "priority": "high",
          "body": "Series Alarm {{ payload._id}}: {{ payload.hits.total }}"
        }
      }
    }
  }
}

```

Right after the first run, I get this error:

```
/opt/kibana/installedPlugins/kaae/server/lib/scheduler.js:87
          server.log(['status', 'info', 'KaaE'], 'Executing watch: ' + task._id + ' Next Round at ' + _later2['default'].schedule(interval).next(2).split(',')[1]);
                                                                                                                                                    ^

TypeError: _later2.default.schedule(...).next(...).split is not a function
    at watching (/opt/kibana/installedPlugins/kaae/server/lib/scheduler.js:70:132)
    at /opt/kibana/installedPlugins/kaae/server/lib/scheduler.js:64:69
    at [object Object].scheduleTimeout [as _onTimeout] (/opt/kibana/installedPlugins/kaae/node_modules/later/later.js:846:9)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by lmangani** [comment]
Thanks for your report @guilhermef 
Could you kindly try replace with the latest build? 
https://github.com/elasticfence/kaae/releases/download/snapshot/kaae-latest.tar.gz

**Comment by guilhermef** [comment]
@lmangani That's the one I'm using right now

**Comment by lmangani** [comment]
I just pushed a new one a second before posting - our ```Nightly``` is also ```Eveningly``` when needed ;)

**Comment by guilhermef** [comment]
Sorry, I didn't knew that, I'll test it now.

**Comment by guilhermef** [comment]
@lmangani Now It's working, but I still get an error when it runs:

```
Trace: { [Error: [mapper_parsing_exception] Field name [95.0] cannot contain '.']
  status: 400,
  message: '[mapper_parsing_exception] Field name [95.0] cannot contain \'.\'',
  path: '/watcher_alarms-2016.10.19/email_admin',
  query: { op_type: 'create' },
  body:
   { error:
      { root_cause: [Object],
        type: 'mapper_parsing_exception',
        reason: 'Field name [95.0] cannot contain \'.\'' },
     status: 400 },
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Field name [95.0] cannot contain \'.\'"}],"type":"mapper_parsing_exception","reason":"Field name [95.0] cannot contain \'.\'"},"status":400}',
  toString: [Function],
  toJSON: [Function] } undefined
    at /opt/kibana/installedPlugins/kaae/server/lib/actions.js:77:22
    at tryCatcher (/opt/kibana/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/kibana/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/opt/kibana/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/opt/kibana/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/opt/kibana/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/kibana/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/kibana/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

But it's look related to: https://github.com/elasticfence/kaae/issues/40

**Comment by lmangani** [comment]
Hey @guilhermef try to delete completely the ```ẁatcher``` index, the latest version has mapping allowing dot fields, if you could give that a shot and confirm your results in #40 it would be great

**Comment by guilhermef** [comment]
Sure, I'll do it, thanks @lmangani
